import type { DataRow, InfographicConfig } from './infographic';
import type { DatasetMeta } from './dataSources';
import type { ViewMode } from './types';

export type CuratedDataset = {
  id: string;
  title: string;
  category: 'Economics' | 'Demographics' | 'Climate & Energy' | 'Governance & Politics';
  viewMode: ViewMode;
  description: string;
  source: string;
  unit: string;
  prefix?: string;
  suffix?: string;
  decimals?: number;
  paletteId: string;
  rows: DataRow[];
  meta: Partial<DatasetMeta>;
  configPatch?: Partial<InfographicConfig>;
};

export const CURATED_DATASETS: CuratedDataset[] = [
  {
    id: 'india_state_gsdp',
    title: 'India State-wise GSDP (2023–24)',
    category: 'Economics',
    viewMode: 'india',
    description: 'Gross State Domestic Product in ₹ Lakh Crore across Indian states and union territories.',
    source: 'Ministry of Statistics and Programme Implementation (MOSPI) · FY 2023-24',
    unit: '₹ Lakh Cr',
    prefix: '₹',
    suffix: ' L Cr',
    decimals: 1,
    paletteId: 'ladakh',
    meta: {
      publisher: 'MOSPI, Government of India',
      releaseDate: '2024-03-31',
      notes: 'State GSDP at current prices (2023-24 advance estimates)',
      synthetic: false,
    },
    rows: [
      ['Maharashtra', 38.8],
      ['Tamil Nadu', 28.3],
      ['Gujarat', 25.6],
      ['Karnataka', 25.0],
      ['Uttar Pradesh', 24.4],
      ['West Bengal', 17.2],
      ['Rajasthan', 15.7],
      ['Andhra Pradesh', 14.4],
      ['Telangana', 14.0],
      ['Madhya Pradesh', 13.9],
      ['Kerala', 11.3],
      ['Delhi', 10.4],
      ['Haryana', 10.2],
      ['Bihar', 8.6],
      ['Odisha', 8.4],
      ['Punjab', 7.4],
      ['Assam', 5.7],
      ['Chhattisgarh', 5.1],
      ['Jharkhand', 4.4],
      ['Uttarakhand', 3.3],
      ['Himachal Pradesh', 2.1],
      ['Jammu and Kashmir', 2.3],
      ['Goa', 1.0],
      ['Tripura', 0.8],
      ['Puducherry', 0.5],
      ['Meghalaya', 0.5],
      ['Manipur', 0.4],
      ['Nagaland', 0.4],
      ['Arunachal Pradesh', 0.4],
      ['Sikkim', 0.5],
      ['Mizoram', 0.4],
      ['Ladakh', 0.1],
      ['Andaman and Nicobar', 0.1],
      ['Chandigarh', 0.6],
      ['Dadra and Nagar Haveli and Daman and Diu', 0.4],
    ].map(([region, val], idx) => ({
      id: `in-gsdp-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2024',
      raw: { State: String(region), GSDP_LakhCr: Number(val) },
    })),
  },
  {
    id: 'india_clean_energy',
    title: 'India Renewable Energy Capacity (GW)',
    category: 'Climate & Energy',
    viewMode: 'india',
    description: 'Installed solar, wind, and small-hydro capacity by state.',
    source: 'Ministry of New and Renewable Energy (MNRE) · 2024 Report',
    unit: 'GW',
    suffix: ' GW',
    decimals: 1,
    paletteId: 'emerald',
    meta: {
      publisher: 'MNRE / Central Electricity Authority',
      releaseDate: '2024-06-30',
      notes: 'Installed renewable power capacity (excluding large hydro)',
      synthetic: false,
    },
    rows: [
      ['Rajasthan', 28.4],
      ['Gujarat', 25.8],
      ['Tamil Nadu', 21.2],
      ['Karnataka', 19.6],
      ['Maharashtra', 16.4],
      ['Andhra Pradesh', 11.8],
      ['Madhya Pradesh', 9.5],
      ['Telangana', 8.2],
      ['Uttar Pradesh', 5.6],
      ['Punjab', 2.8],
      ['Haryana', 2.4],
      ['Kerala', 1.9],
      ['Odisha', 1.7],
      ['Uttarakhand', 1.4],
      ['Himachal Pradesh', 1.3],
      ['West Bengal', 0.8],
      ['Jammu and Kashmir', 0.5],
      ['Bihar', 0.4],
      ['Assam', 0.3],
      ['Chhattisgarh', 0.9],
      ['Goa', 0.1],
    ].map(([region, val], idx) => ({
      id: `in-re-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2024',
      raw: { State: String(region), Capacity_GW: Number(val) },
    })),
  },
  {
    id: 'india_literacy_rate',
    title: 'India State-wise Literacy Rate (%)',
    category: 'Demographics',
    viewMode: 'india',
    description: 'Effective literacy rate across states and UTs.',
    source: 'National Statistical Office (NSO) / Census of India',
    unit: '%',
    suffix: '%',
    decimals: 1,
    paletteId: 'kochi',
    meta: {
      publisher: 'National Statistical Office (NSO)',
      releaseDate: '2023-11-15',
      notes: 'State literacy rate among population aged 7 and above',
      synthetic: false,
    },
    rows: [
      ['Kerala', 96.2],
      ['Delhi', 88.7],
      ['Uttarakhand', 87.6],
      ['Himachal Pradesh', 86.6],
      ['Assam', 85.9],
      ['Maharashtra', 84.8],
      ['Punjab', 83.7],
      ['Tamil Nadu', 82.9],
      ['Gujarat', 82.4],
      ['West Bengal', 80.5],
      ['Haryana', 80.4],
      ['Karnataka', 77.2],
      ['Odisha', 77.3],
      ['Chhattisgarh', 77.3],
      ['Madhya Pradesh', 73.7],
      ['Uttar Pradesh', 73.0],
      ['Jharkhand', 74.3],
      ['Rajasthan', 69.7],
      ['Bihar', 70.9],
      ['Andhra Pradesh', 66.4],
      ['Telangana', 72.8],
      ['Goa', 88.7],
      ['Tripura', 87.2],
      ['Mizoram', 91.3],
      ['Nagaland', 79.6],
      ['Meghalaya', 74.4],
      ['Manipur', 76.9],
      ['Sikkim', 81.4],
      ['Jammu and Kashmir', 77.3],
      ['Ladakh', 77.5],
    ].map(([region, val], idx) => ({
      id: `in-lit-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2023',
      raw: { State: String(region), LiteracyRate: Number(val) },
    })),
  },
  {
    id: 'world_top_gdp',
    title: 'World Top Economies by Nominal GDP ($ Trillion)',
    category: 'Economics',
    viewMode: 'world',
    description: 'Current nominal GDP in Trillion US Dollars for major global economies.',
    source: 'World Bank WDI · IMF World Economic Outlook 2024',
    unit: '$ Trillion',
    prefix: '$',
    suffix: 'T',
    decimals: 2,
    paletteId: 'viridis',
    meta: {
      publisher: 'World Bank / IMF',
      releaseDate: '2024-10-01',
      notes: 'Nominal GDP at current market exchange rates',
      synthetic: false,
    },
    rows: [
      ['United States of America', 29.3],
      ['China', 18.7],
      ['Germany', 4.7],
      ['Japan', 4.2],
      ['India', 3.9],
      ['United Kingdom', 3.5],
      ['France', 3.1],
      ['Italy', 2.3],
      ['Brazil', 2.2],
      ['Canada', 2.2],
      ['Russia', 2.1],
      ['Mexico', 1.8],
      ['Australia', 1.7],
      ['South Korea', 1.7],
      ['Spain', 1.6],
      ['Indonesia', 1.4],
      ['Netherlands', 1.1],
      ['Saudi Arabia', 1.1],
      ['Turkey', 1.1],
      ['Switzerland', 0.9],
      ['Poland', 0.9],
      ['Argentina', 0.6],
      ['Sweden', 0.6],
      ['Belgium', 0.6],
      ['Nigeria', 0.4],
      ['South Africa', 0.4],
      ['Egypt', 0.4],
      ['Singapore', 0.5],
      ['United Arab Emirates', 0.5],
    ].map(([region, val], idx) => ({
      id: `w-gdp-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2024',
      raw: { Country: String(region), GDP_TrillionUSD: Number(val) },
    })),
  },
  {
    id: 'world_co2_per_capita',
    title: 'Global CO2 Emissions per Capita (Tons/Year)',
    category: 'Climate & Energy',
    viewMode: 'world',
    description: 'Annual metric tons of CO2 emitted per person across countries.',
    source: 'Global Carbon Project · Our World in Data 2024',
    unit: 't CO2/capita',
    suffix: ' t',
    decimals: 1,
    paletteId: 'magma',
    meta: {
      publisher: 'Global Carbon Atlas / OWID',
      releaseDate: '2024-04-12',
      notes: 'Production-based territorial CO2 emissions per capita',
      synthetic: false,
    },
    rows: [
      ['Qatar', 35.6],
      ['United Arab Emirates', 21.8],
      ['Saudi Arabia', 18.2],
      ['Australia', 15.1],
      ['United States of America', 14.9],
      ['Canada', 14.3],
      ['Russia', 12.1],
      ['South Korea', 11.6],
      ['Japan', 8.5],
      ['China', 8.0],
      ['Germany', 7.9],
      ['Poland', 7.5],
      ['South Africa', 6.9],
      ['Italy', 5.3],
      ['United Kingdom', 4.7],
      ['France', 4.2],
      ['Spain', 4.8],
      ['Turkey', 5.1],
      ['Mexico', 3.6],
      ['Argentina', 3.8],
      ['Brazil', 2.3],
      ['Indonesia', 2.6],
      ['India', 2.0],
      ['Egypt', 2.4],
      ['Nigeria', 0.6],
      ['Bangladesh', 0.6],
    ].map(([region, val], idx) => ({
      id: `w-co2-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2024',
      raw: { Country: String(region), CO2_Tons_PerCapita: Number(val) },
    })),
  },
  {
    id: 'usa_state_gdp',
    title: 'USA State GDP ($ Billion)',
    category: 'Economics',
    viewMode: 'usa',
    description: 'Nominal Gross Domestic Product by US State in Billions of Dollars.',
    source: 'Bureau of Economic Analysis (BEA) · 2024',
    unit: '$B',
    prefix: '$',
    suffix: 'B',
    decimals: 0,
    paletteId: 'bengaluru',
    meta: {
      publisher: 'U.S. Bureau of Economic Analysis',
      releaseDate: '2024-06-20',
      notes: 'Real-time state GDP quarterly annualized',
      synthetic: false,
    },
    rows: [
      ['California', 3900],
      ['Texas', 2600],
      ['New York', 2150],
      ['Florida', 1600],
      ['Illinois', 1080],
      ['Pennsylvania', 970],
      ['Ohio', 875],
      ['Georgia', 830],
      ['Washington', 805],
      ['New Jersey', 795],
      ['North Carolina', 760],
      ['Massachusetts', 735],
      ['Virginia', 705],
      ['Michigan', 660],
      ['Colorado', 530],
      ['Tennessee', 525],
      ['Arizona', 505],
      ['Indiana', 495],
      ['Minnesota', 470],
      ['Maryland', 485],
      ['Wisconsin', 415],
      ['Missouri', 420],
      ['Connecticut', 340],
      ['South Carolina', 320],
      ['Oregon', 315],
      ['Louisiana', 310],
      ['Alabama', 300],
      ['Kentucky', 275],
      ['Utah', 270],
      ['Oklahoma', 250],
      ['Iowa', 245],
      ['Nevada', 235],
      ['Kansas', 225],
      ['Arkansas', 175],
      ['Nebraska', 180],
      ['Mississippi', 145],
      ['New Mexico', 135],
      ['Idaho', 120],
      ['New Hampshire', 115],
      ['Hawaii', 110],
      ['West Virginia', 100],
      ['Delaware', 95],
      ['Maine', 90],
      ['Rhode Island', 75],
      ['North Dakota', 75],
      ['South Dakota', 70],
      ['Montana', 70],
      ['Alaska', 65],
      ['Wyoming', 50],
      ['Vermont', 42],
    ].map(([region, val], idx) => ({
      id: `usa-gdp-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2024',
      raw: { State: String(region), GDP_BillionUSD: Number(val) },
    })),
  },
  {
    id: 'uttarakhand_district_pop',
    title: 'Uttarakhand District Population (Lakhs)',
    category: 'Demographics',
    viewMode: 'district',
    description: 'District-wise population distribution in Uttarakhand.',
    source: 'Census of India · Uttarakhand State Portal',
    unit: 'Lakh',
    suffix: ' L',
    decimals: 2,
    paletteId: 'ladakh',
    meta: {
      publisher: 'Directorate of Census Operations, Uttarakhand',
      releaseDate: '2022-01-01',
      notes: 'District-wise population estimates in Lakhs (100,000s)',
      synthetic: false,
    },
    rows: [
      ['Haridwar', 18.90],
      ['Dehradun', 16.96],
      ['Udham Singh Nagar', 16.48],
      ['Nainital', 9.55],
      ['Pauri Garhwal', 6.87],
      ['Almora', 6.22],
      ['Tehri Garhwal', 6.18],
      ['Pithoragarh', 4.83],
      ['Chamoli', 3.91],
      ['Uttarkashi', 3.30],
      ['Bageshwar', 2.59],
      ['Champawat', 2.59],
      ['Rudraprayag', 2.42],
    ].map(([region, val], idx) => ({
      id: `uk-pop-${idx + 1}`,
      region: String(region),
      value: Number(val),
      year: '2022',
      raw: { District: String(region), Population_Lakh: Number(val) },
    })),
  },
];
