import { ArrowUpRight, Check, Eye, EyeOff, FileImage, MapPinned, Palette, PanelRight, SlidersHorizontal, Trash2, Type } from 'lucide-react';
import { PALETTES, type Annotation, type InfographicConfig } from '../domain/infographic';
import type { EditorMode, StyleSpec } from '../domain/types';

type Props = {
  editorMode: EditorMode;
  style: StyleSpec;
  hiddenLayers: Record<string, boolean>;
  config: InfographicConfig;
  annotations: Annotation[];
  onStyle: (patch: Partial<StyleSpec>) => void;
  onToggle: (layer: string) => void;
  onConfig: (patch: Partial<InfographicConfig>) => void;
  onAnnotations: (annotations: Annotation[]) => void;
};

const baseColors = ['#6479e8', '#3da58c', '#dc6b65', '#cf8b42', '#7c63b4', '#24324a'];

export function InfographicEditorPanel({ editorMode, style, hiddenLayers, config, annotations, onStyle, onToggle, onConfig, onAnnotations }: Props) {
  const addAnnotation = (type: Annotation['type']) => onAnnotations([...annotations, { id: crypto.randomUUID(), type, text: type === 'text' ? 'Add insight' : type === 'marker' ? 'Key location' : 'Look here', x: 50, y: 45, color: '#24324a', size: 13 }]);
  const updateAnnotation = (id: string, patch: Partial<Annotation>) => onAnnotations(annotations.map((annotation) => annotation.id === id ? { ...annotation, ...patch } : annotation));

  return <div className="panel-content infographic-editor"><div className="editor-heading"><div><span className="eyebrow">{editorMode === 'editor' ? 'INFOGRAPHIC EDITOR' : 'VIEWER MODE'}</span><h2>{editorMode === 'editor' ? 'Design your data story' : 'Explore the map'}</h2></div><PanelRight size={17} className="muted-icon" /></div>{editorMode === 'viewer' ? <div className="empty-panel viewer-hint"><Eye size={21} /><strong>Read-only preview</strong><span>Switch to Editor to change colours, labels, titles, and annotations.</span></div> : <>
    <div className="editor-section"><div className="section-title"><span><Type size={14} /> Story</span></div><label className="field-row"><span>Title</span><input value={config.title} onChange={(event) => onConfig({ title: event.target.value })} /></label><label className="field-row"><span>Subtitle</span><input value={config.subtitle} onChange={(event) => onConfig({ subtitle: event.target.value })} /></label><label className="field-row"><span>Source</span><input value={config.source} onChange={(event) => onConfig({ source: event.target.value })} /></label><div className="toggle-grid"><label><input type="checkbox" checked={config.showTitle} onChange={(event) => onConfig({ showTitle: event.target.checked })} /> Title</label><label><input type="checkbox" checked={config.showLegend} onChange={(event) => onConfig({ showLegend: event.target.checked })} /> Legend</label><label><input type="checkbox" checked={config.showSource} onChange={(event) => onConfig({ showSource: event.target.checked })} /> Source</label></div></div>
    <div className="editor-section"><div className="section-title"><span><Palette size={14} /> Data palette</span><button className="text-button" onClick={() => { onConfig({ paletteId: 'ladakh' }); onStyle({ fill: '#6479e8', opacity: .78 }); }}>Reset</button></div><div className="palette-presets">{PALETTES.map((palette) => <button className={config.paletteId === palette.id ? 'active' : ''} key={palette.id} onClick={() => onConfig({ paletteId: palette.id })}><span>{palette.colors.map((color) => <i key={color} style={{ background: color }} />)}</span><small>{palette.label}</small>{config.paletteId === palette.id && <Check size={11} />}</button>)}</div><div className="base-color-row">{baseColors.map((color) => <button key={color} className={style.fill === color ? 'active' : ''} style={{ background: color }} onClick={() => onStyle({ fill: color })} aria-label={`Base colour ${color}`} />)}</div><label className="range-row"><span>Map opacity</span><output>{Math.round(style.opacity * 100)}%</output><input type="range" min="0.2" max="1" step="0.02" value={style.opacity} onChange={(event) => onStyle({ opacity: Number(event.target.value) })} /></label></div>
    <div className="editor-section"><div className="section-title"><span><SlidersHorizontal size={14} /> Scale and missing data</span></div><label className="select-row"><span>Scale</span><select value={config.scaleMode} onChange={(event) => onConfig({ scaleMode: event.target.value as InfographicConfig['scaleMode'] })}><option value="continuous">Continuous</option><option value="equal">Equal intervals</option><option value="quantile">Quantiles</option><option value="categorical">Categories / parties</option><option value="custom">Custom breaks</option></select></label>{config.scaleMode !== 'categorical' && <label className="select-row"><span>Classes</span><select value={config.classes} onChange={(event) => onConfig({ classes: Number(event.target.value) })}>{[3,4,5,6,7,8].map((value) => <option key={value}>{value}</option>)}</select></label>}{config.scaleMode === 'custom' && <label className="field-row"><span>Breaks</span><input value={config.customBreaks} onChange={(event) => onConfig({ customBreaks: event.target.value })} placeholder="10, 25, 50, 75" /></label>}<label className="select-row"><span>Missing</span><select value={config.missingMode} onChange={(event) => onConfig({ missingMode: event.target.value as InfographicConfig['missingMode'] })}><option value="grey">Grey</option><option value="white">White</option><option value="hide">Hide</option></select></label><label className="select-row"><span>Zero</span><select value={config.zeroMode} onChange={(event) => onConfig({ zeroMode: event.target.value as InfographicConfig['zeroMode'] })}><option value="normal">Use scale</option><option value="grey">Grey</option><option value="white">White</option><option value="hide">Hide</option></select></label></div>
    <div className="editor-section"><div className="section-title"><span><Type size={14} /> Labels</span><button className="layer-eye" onClick={() => onToggle('labels')}>{hiddenLayers.labels ? <EyeOff size={15} /> : <Eye size={15} />}</button></div><label className="select-row"><span>Content</span><select value={config.labelMode} onChange={(event) => onConfig({ labelMode: event.target.value as InfographicConfig['labelMode'] })}><option value="name">Region name</option><option value="value">Data value</option><option value="both">Name + value</option><option value="none">No labels</option></select></label><div className="inline-fields"><label><span>Prefix</span><input value={config.prefix} onChange={(event) => onConfig({ prefix: event.target.value })} placeholder="₹" /></label><label><span>Suffix</span><input value={config.suffix} onChange={(event) => onConfig({ suffix: event.target.value })} placeholder="%" /></label></div><label className="select-row"><span>Number style</span><select value={config.numberFormat} onChange={(event) => onConfig({ numberFormat: event.target.value as InfographicConfig['numberFormat'] })}><option value="standard">Indian commas</option><option value="indian">Lakh / crore</option><option value="metric">K / M / B</option></select></label></div>
    <div className="editor-section"><div className="section-title"><span><MapPinned size={14} /> Annotations</span></div><div className="annotation-grid"><button onClick={() => addAnnotation('text')}><Type size={15} /><span>Text</span></button><button onClick={() => addAnnotation('marker')}><MapPinned size={15} /><span>Marker</span></button><button onClick={() => addAnnotation('arrow')}><ArrowUpRight size={15} /><span>Arrow</span></button><button onClick={() => onConfig({ showLegend: !config.showLegend })}><FileImage size={15} /><span>Legend</span></button></div>{annotations.map((annotation) => <div className="annotation-edit-row" key={annotation.id}><input value={annotation.text} onChange={(event) => updateAnnotation(annotation.id, { text: event.target.value })} /><input type="color" value={annotation.color} onChange={(event) => updateAnnotation(annotation.id, { color: event.target.value })} /><button onClick={() => onAnnotations(annotations.filter((item) => item.id !== annotation.id))}><Trash2 size={13} /></button></div>)}<p className="panel-note">Drag annotations directly on the map to position them.</p></div>
    <div className="editor-section"><div className="section-title"><span><FileImage size={14} /> Canvas</span></div><label className="select-row"><span>Aspect</span><select value={config.aspect} onChange={(event) => onConfig({ aspect: event.target.value as InfographicConfig['aspect'] })}><option value="16:9">16:9 landscape</option><option value="1:1">Square</option><option value="4:5">4:5 portrait</option><option value="9:16">9:16 story</option><option value="a4">A4 portrait</option></select></label><label className="select-row"><span>Export</span><select value={config.resolution} onChange={(event) => onConfig({ resolution: event.target.value as InfographicConfig['resolution'] })}><option value="hd">HD</option><option value="4k">4K</option></select></label><label className="color-row"><span>Background</span><input type="color" value={config.background} onChange={(event) => onConfig({ background: event.target.value })} /></label></div>
  </>}</div>;
}
